version: '3.8'

services:
  docx-unpacker-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docx-unpacker-web
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
    networks:
      - nginx-proxy-network
    expose:
      - "3000"

networks:
  nginx-proxy-network:
    external: true
    name: nginx-proxy